server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: summer-training-backend
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/pricecompare?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    sql:
      init:
        mode: never
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
          
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false
      
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

# 日志配置
logging:
  level:
    com.bijiabao: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 自定义配置
app:
  name: 'My Application'
  jwt:
    secret: bijiabao-secret-key-2024
    expiration: 86400000 # 24小时
  cors:
    allowed-origins: 
      - http://localhost:5173
      - http://127.0.0.1:5173
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Content-Type
      - Authorization
      - X-Requested-With
    allow-credentials: true
  upload:
    path: ./uploads
    max-size: 10MB
  prediction:
    default-strategy: simple
    cache-enabled: true
    cache-ttl: 300 # 5分钟